[package]
name = "rusttactoe"
version = "0.1.0"
authors = ["Bjarke Sørensen <bs@wasd.dk>"]
edition = "2024"

[dependencies]
text_io = "0.1.7"
ansi_term = "0.12.0"
rand = "0.9.2"

[features]
# Show what the eval bot is thinking
show-eval = []
